#!/usr/bin/env python3
"""Run the configs GENERATED BY scripts/install.sh (edge + remote, --root
mode) in the netns lab: edge = listener namespace (192.0.2.2), remote =
dialer namespace. Verifies the tunnel comes up on the generated carrier list,
traffic flows, tunnelctl doctor works against the generated API socket, and
failover tcp/443 -> quic/443 works with the generated ports.

  sudo python3 tests/lab/install_check.py EDGE_ROOT REMOTE_ROOT out.json
"""
import json, os, re, subprocess, sys, time
sys.path.insert(0, os.path.dirname(__file__))
from labkit import Lab, BIN

edge, remote, out = sys.argv[1], sys.argv[2], sys.argv[3]
lab = Lab("in", impair=False)
R, ok = {}, False
try:
    lab.up()
    for who, root in (("b", edge), ("a", remote)):
        cfg = open(f"{root}/etc/tuunel/config.yaml").read()
        open(f"{lab.w}/{who}.yaml", "w").write(cfg)
        sock = re.search(r"socket: (\S+)\}", cfg).group(1)
        os.symlink(sock, f"{lab.w}/{who}.sock")
        R[f"{who}_socket"] = sock
    lab.start("b"); time.sleep(0.5); lab.start("a")
    R["up_tcp443_s"] = lab.wait_carrier("tcp/.*", 20)
    R["ping_remote_to_edge"] = lab.ping("10.200.0.1", count=30, interval=0.02)
    R["tcp_remote_to_edge"] = lab.iperf(2, dst="10.200.0.1")
    r = subprocess.run(["ip", "netns", "exec", lab.nb, "timeout", "25", f"{BIN}/tunnelctl", "-socket", R["b_socket"],
                        "-config", f"{edge}/etc/tuunel/config.yaml", "doctor"], capture_output=True, text=True, timeout=30)
    R["doctor_rc"], R["doctor_tail"] = r.returncode, (r.stdout + r.stderr).strip().splitlines()[-6:]
    sub = subprocess.run(["ip", "netns", "exec", lab.nb, "nft", "-f", "-"], input=
                         'table ip tlab {\n chain tin {\n  type filter hook input priority 0; policy accept;\n'
                         '  iifname "vb" tcp dport 443 drop\n }\n}\n', capture_output=True, text=True, timeout=10)
    R["failover_to_quic443_s"] = lab.wait_carrier("quic/.*", 30)
    R["ping_after_failover"] = lab.ping("10.200.0.1", count=20, interval=0.05)
    lab.B("nft delete table ip tlab")
    lab.stop("a"); R["edge_exit"] = lab.stop("b")
    ok = (R["up_tcp443_s"] is not None and R["ping_remote_to_edge"]["loss_pct"] == 0 and
          (R["tcp_remote_to_edge"].get("mbit") or 0) > 10 and R["failover_to_quic443_s"] is not None and
          R["ping_after_failover"]["loss_pct"] <= 10 and R["edge_exit"] == 0)
finally:
    lab.cleanup()
R["result"] = "PASS" if ok else "FAIL"
json.dump(R, open(out, "w"), indent=1)
print(json.dumps(R, indent=1))
sys.exit(0 if ok else 1)
